from pathlib import Path

p = Path('web/config.html')
s = p.read_text(encoding='utf-8')


def must_replace(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f'Could not locate {label}')
    s = s.replace(old, new, 1)


must_replace('<title>FreeCLinker — Config</title>', '<title>FreeCLinker — FPSteVe Edition Config</title>', 'page title')
must_replace('<span class="brand">FreeCLinker</span>', '<span class="brand">FreeCLinker — FPSteVe Edition</span>', 'brand')
must_replace('</head>', '  <link rel="stylesheet" href="fps-theme.css">\n</head>', 'head close')
must_replace('  <button class="tab"        data-tab="cli">CLI</button>\n</div>', '  <button class="tab"        data-tab="cli">CLI</button>\n  <a class="tab osd-preview-tab" href="test.html">OSD Preview</a>\n</div>', 'OSD Preview tab')

start_marker = '      <div class="cfg-field" style="flex-direction:column;align-items:flex-start;">\n        <div class="cfg-field-name">State-aware Craft Name</div>'
end_marker = '      <div class="card-footer">'
start = s.find(start_marker); end = s.find(end_marker, start)
if start == -1 or end == -1: raise SystemExit('Could not locate FPSteVe state/warning section')
lines = [
'      <div class="cfg-field" style="flex-direction:column;align-items:flex-start;">','        <div style="display:none"><input type="checkbox" id="fpvStateMode" checked></div>','',
'        <div style="width:100%;"><strong>Custom Message</strong><div class="cfg-field-desc">Optional message shown periodically. Leave blank to disable.</div></div>',
'        <div style="display:flex;align-items:center;gap:10px;width:100%;margin-top:10px;"><label for="fpvPreArmText" style="min-width:185px;">Message</label><input class="tpl-input" type="text" id="fpvPreArmText" maxlength="16" placeholder="e.g. CLEAN LENS" spellcheck="false" style="margin-top:0;flex:1;min-width:0;"></div>',
'        <div style="display:flex;align-items:center;justify-content:space-between;width:100%;margin-top:12px;"><div><strong>Only before first arm</strong><div class="cfg-field-desc">Stop showing after the first arm until the next power cycle.</div></div><label class="switch"><input type="checkbox" id="fpvPreArm"><span class="track"><span class="thumb"></span></span></label></div>',
'        <div style="display:flex;align-items:center;gap:10px;width:100%;margin-top:12px;"><label for="fpvCustomDurationSec" style="min-width:185px;">Display duration</label><input type="number" id="fpvCustomDurationSec" min="0.1" max="2.5" step="0.1" value="1.0" style="width:90px;"><span class="num-unit">sec</span></div>',
'        <div style="display:none"><input type="number" id="fpvPreArmShow" value="1000"><input type="number" id="fpvPreArmInt" value="3000"></div>','',
'        <div style="display:flex;align-items:center;justify-content:space-between;width:100%;margin-top:20px;"><div><strong>Camera warnings</strong><div class="cfg-field-desc">Low battery, low recording-time and camera-hot warnings.</div></div><label class="switch"><input type="checkbox" id="fpvLowBatt"><span class="track"><span class="thumb"></span></span></label></div>',
'        <div style="display:flex;align-items:center;gap:10px;width:100%;margin-top:14px;"><label for="fpvLowPct" style="min-width:185px;">Low battery threshold</label><input type="number" id="fpvLowPct" min="0" max="100" step="1" value="10" style="width:90px;"><span class="num-unit">%</span></div>',
'        <div style="display:flex;align-items:center;gap:10px;width:100%;margin-top:12px;"><label for="fpvRecLowMin" style="min-width:185px;">Low recording-time threshold</label><input type="number" id="fpvRecLowMin" min="0" max="999" step="1" value="5" style="width:90px;"><span class="num-unit">min</span></div>',
'        <div class="cfg-field-desc" style="margin-top:8px;">Camera-hot uses camera over-temperature status automatically.</div>','',
'        <div style="display:none">','          <input type="checkbox" id="fpvError" checked><input id="fpvErrorText" value="{state} {batt} {rectf}">','          <input type="checkbox" id="fpvReady" checked><input id="fpvReadyText" value="{state} {batt} {rectf}">','          <input type="checkbox" id="fpvRecord" checked><input id="fpvRecordText" value="{state}"><input type="checkbox" id="fpvFlash" checked>','          <input id="fpvLowText" value="BATT LOW"><input type="checkbox" id="fpvLowRdyFlash" checked><input type="checkbox" id="fpvLowRecText" checked>','          <input type="checkbox" id="fpvRecLow" checked><input id="fpvRecLowText" value="REC LOW"><input type="checkbox" id="fpvRecLowReady" checked><input type="checkbox" id="fpvRecLowRecording" checked>','          <input type="checkbox" id="fpvHot" checked><input id="fpvHotText" value="CAM HOT"><input type="checkbox" id="fpvHotReady" checked><input type="checkbox" id="fpvHotRecording" checked>','        </div>','      </div>','']
s=s[:start]+'\n'.join(lines)+s[end:]

hook="[fpvStateModeToggle, fpvErrorToggle, fpvReadyToggle, fpvRecordToggle, fpvFlashToggle, fpvLowBattToggle, fpvRecLowToggle, fpvHotToggle].forEach(el => el.addEventListener('change', updateFpvOptionState));"
must_replace(hook,hook+"\nfpvLowBattToggle.addEventListener('change',()=>{fpvRecLowToggle.checked=fpvLowBattToggle.checked;fpvHotToggle.checked=fpvLowBattToggle.checked;updateFpvOptionState();});\nconst customDurationInput=document.getElementById('fpvCustomDurationSec');customDurationInput.addEventListener('input',()=>{const sec=Math.min(2.5,Math.max(0.1,parseFloat(customDurationInput.value)||1));fpvPreArmShowInput.value=Math.round(sec*1000);});",'FPS option hook')
must_replace("  const key = m[1];\n  const val = m[2].trim().replace(/\\s*\\(saved.*/, '');","  const key = m[1];\n  const val = m[2].trim().replace(/\\s*\\(saved.*/, '');\n  try{const c=JSON.parse(localStorage.getItem('freeclinkerC3Config')||'{}');c[key]=val;localStorage.setItem('freeclinkerC3Config',JSON.stringify(c));}catch{}",'cache hook')
must_replace("} else if (key === 'fpv_state_mode') { fpvStateModeToggle.checked = (val === 'true');","} else if (key === 'fpv_state_mode') { fpvStateModeToggle.checked = true;",'state parser')
must_replace("} else if (key === 'fpv_prearm_show') { fpvPreArmShowInput.value = parseInt(val) || 1000;","} else if (key === 'fpv_prearm_show') { fpvPreArmShowInput.value=parseInt(val)||1000; const d=document.getElementById('fpvCustomDurationSec');if(d)d.value=(Math.min(2500,Math.max(100,fpvPreArmShowInput.value))/1000).toFixed(1);",'duration parser')
fix=[("  await sendCommand(`set fpv_state_mode ${fpvStateModeToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_state_mode 1');"),("  await sendCommand(`set fpv_error ${fpvErrorToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_error 1');"),("  await sendCommand(`set fpv_ready ${fpvReadyToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_ready 1');"),("  await sendCommand(`set fpv_record ${fpvRecordToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_record 1');"),("  await sendCommand(`set fpv_low_rdyflash ${fpvLowRdyFlashToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_low_rdyflash 1');"),("  await sendCommand(`set fpv_low_rectext ${fpvLowRecTextToggle.checked ? 1 : 0}`);","  await sendCommand('set fpv_low_rectext 1');"),("  await sendCommand(`set fpv_rect_warn ${fpvRecLowToggle.checked ? 1 : 0}`);","  await sendCommand(`set fpv_rect_warn ${fpvLowBattToggle.checked ? 1 : 0}`);"),("  await sendCommand(`set fpv_hot_warn ${fpvHotToggle.checked ? 1 : 0}`);","  await sendCommand(`set fpv_hot_warn ${fpvLowBattToggle.checked ? 1 : 0}`);")]
for a,b in fix: must_replace(a,b,'fixed command')
must_replace("  await sendCommand(`set fpv_prearm_show ${Math.max(100, parseInt(fpvPreArmShowInput.value) || 1000)}`);","  const customMsgSec=Math.min(2.5,Math.max(0.1,parseFloat(document.getElementById('fpvCustomDurationSec').value)||1));\n  await sendCommand(`set fpv_prearm_show ${Math.round(customMsgSec*1000)}`);",'duration apply')
must_replace("  await sendCommand(`set fpv_prearm_int ${Math.max(100, parseInt(fpvPreArmIntInput.value) || 3000)}`);","  await sendCommand('set fpv_prearm_int 3000');",'interval apply')

# Keep demo persistence here; the actual OSD builder is a normal versioned web asset.
demo=r'''<style id="fps-demo-style">.demo-banner{display:none;background:#3b1766;color:#f2e8ff;padding:8px;text-align:center;font-weight:700}.demo-on .demo-banner{display:block}</style><script id="fps-demo">(()=>{const MODE='freeclinkerDemoMode',CFG='freeclinkerDemoConfig';let demo=localStorage.getItem(MODE)==='1';const banner=document.createElement('div');banner.className='demo-banner';banner.textContent='DEMO MODE — DEMO DATA — NO HARDWARE REQUIRED';document.body.insertBefore(banner,document.body.firstChild);const btn=document.createElement('button');btn.type='button';btn.id='demoModeBtn';btn.textContent=demo?'Exit Demo':'Demo Mode';const connect=document.getElementById('connectBtn');if(connect)connect.parentNode.insertBefore(btn,connect);const fields=()=>[...document.querySelectorAll('#panel-config input[id],#panel-config select[id]')].filter(e=>e.id!=='caddxPass'),snap=()=>Object.fromEntries(fields().map(e=>[e.id,e.type==='checkbox'?e.checked:e.value]));function save(){if(!demo)return;const d=snap();localStorage.setItem(CFG,JSON.stringify(d));const old=JSON.parse(localStorage.getItem('freeclinkerC3Config')||'{}');localStorage.setItem('freeclinkerC3Config',JSON.stringify({...old,osd1:d.osd1||'',osd2:d.osd2||'',osd3:d.osd3||'',osd4:d.osd4||'',bf45_compat:d.bf45Compat?'true':'false',pilot_tpl:d.pilotTpl||'',craft_tpl:d.craftTpl||'',fpv_prearm_text:d.fpvPreArmText||'',fpv_prearm:d.fpvPreArm?'true':'false',fpv_low_batt:d.fpvLowBatt?'true':'false',fpv_low_pct:String(d.fpvLowPct||10),fpv_rect_min:String(d.fpvRecLowMin||5)}))}function restore(){try{const d=JSON.parse(localStorage.getItem(CFG)||'{}');for(const[id,v]of Object.entries(d)){const e=document.getElementById(id);if(e){e.type==='checkbox'?e.checked=!!v:e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}}}catch{}}function ui(){document.body.classList.toggle('demo-on',demo);if(demo)fields().forEach(e=>e.disabled=false)}btn.onclick=()=>{if(!demo){localStorage.setItem(MODE,'1');localStorage.setItem(CFG,JSON.stringify(snap()))}else{save();localStorage.setItem(MODE,'0')}location.reload()};document.addEventListener('input',e=>{if(demo&&e.target.closest('#panel-config'))save()});document.addEventListener('change',e=>{if(demo&&e.target.closest('#panel-config'))save()});if(demo){restore();ui();save()}})();</script><script src="fps-ui-v2.js"></script><script src="fps-osd-method.js"></script>'''
must_replace('</body>',demo+'\n</body>','demo and UI v2')

for marker in ['id="fpvCustomDurationSec"','Only before first arm','Camera warnings','freeclinkerC3Config','class="tab osd-preview-tab"','fps-demo','fps-ui-v2.js','fps-osd-method.js','freeclinkerDemoMode']:
    if marker not in s: raise SystemExit('Generated configurator missing expected marker: '+marker)
p.write_text(s,encoding='utf-8');print('FPSteVe configurator generated and validated')