(()=>{
'use strict';
const TOKENS=[['Status','{state}'],['Battery','{batt}'],['Recording Duration','{recdur}'],['Mode','{mode}'],['Resolution','{res}'],['FPS','{fps}'],['Stabilisation','{eis}'],['Time Remaining','{rectf}'],['Storage Remaining','{rcap}']];
const SAMPLE={'{state}':'RDY','{batt}':'B:69','{recdur}':'00:42','{mode}':'VIDEO','{res}':'4K','{fps}':'60','{eis}':'HS','{rectf}':'T:45m','{rcap}':'128GB'};
const IDS=['osd1','osd2','osd3','osd4','pilotTpl','craftTpl']; const q=id=>document.getElementById(id);
function sample(v){let s=v||'';for(const[k,x]of Object.entries(SAMPLE))s=s.split(k).join(x);return s.replace(/\s+/g,' ').trim()||'(empty)'}
function tokens(v){return(v||'').match(/\{[^}]+\}/g)||[]}
function setTokens(input,a){input.value=a.join(' ');input.dispatchEvent(new Event('input',{bubbles:true}))}
function rebuild(input,box){const a=tokens(input.value),chips=box.querySelector('.fps-chips');chips.innerHTML='';for(const token of a){const def=TOKENS.find(x=>x[1]===token),chip=document.createElement('span');chip.className='fps-chip';chip.append(document.createTextNode(def?def[0]:token));const x=document.createElement('button');x.type='button';x.textContent='×';x.onclick=()=>{const b=tokens(input.value),i=b.indexOf(token);if(i>=0)b.splice(i,1);setTokens(input,b)};chip.appendChild(x);chips.appendChild(chip)}box.querySelector('.fps-preview').textContent=sample(input.value);for(const cb of box.querySelectorAll('.fps-menu input[type=checkbox]'))cb.checked=a.includes(cb.value);const status=box.querySelector('.fps-local-status');status.classList.toggle('fps-hidden',!a.includes('{state}'))}
function makeBuilder(input,label){const old=input.closest('.osd-builder');if(old){old.parentNode.insertBefore(input,old);old.remove()}const box=document.createElement('div');box.className='fps-builder';box.dataset.input=input.id;box.innerHTML=`<div class="fps-builder-head"><strong>${label}</strong><span class="fps-preview"></span></div><details class="fps-picker"><summary>Add OSD elements…</summary><div class="fps-menu">${TOKENS.map(([n,t])=>`<label><input type="checkbox" value="${t}"> ${n}</label>`).join('')}</div></details><div class="fps-chips"></div><div class="fps-local-status fps-hidden"><strong>Status behaviour</strong><label><input class="fps-rec-only" type="checkbox" checked> While recording show REC only</label><label><input class="fps-flash-rec" type="checkbox" checked> Flash REC while recording</label></div><details class="fps-advanced"><summary>Advanced / raw template</summary><div class="fps-raw"></div></details>`;input.parentNode.insertBefore(box,input);box.querySelector('.fps-raw').appendChild(input);box.querySelectorAll('.fps-menu input').forEach(cb=>cb.onchange=()=>{let a=tokens(input.value);if(cb.checked){if(!a.includes(cb.value))a.push(cb.value)}else a=a.filter(x=>x!==cb.value);setTokens(input,a)});box.querySelector('.fps-flash-rec').onchange=sync;input.addEventListener('input',()=>{rebuild(input,box);sync()});input.addEventListener('change',()=>{rebuild(input,box);sync()});rebuild(input,box);return box}
function activeIds(){return q('bf45Compat')?.checked?['pilotTpl','craftTpl']:['osd1','osd2','osd3','osd4']}
function sync(){const active=new Set(activeIds()),bf45=!!q('bf45Compat')?.checked;for(const id of IDS){const box=q(id)?.closest('.fps-builder');if(!box)continue;box.classList.toggle('fps-disabled',!active.has(id));const has=(q(id).value||'').includes('{state}');box.querySelector('.fps-local-status')?.classList.toggle('fps-hidden',!has)}if(q('fpvRecordText'))q('fpvRecordText').value='{state}';if(q('fpvReadyText'))q('fpvReadyText').value='{state} {batt} {rectf}';if(q('fpvErrorText'))q('fpvErrorText').value='{state} {batt} {rectf}';const statusBoxes=[...document.querySelectorAll('.fps-builder:not(.fps-disabled) .fps-local-status:not(.fps-hidden)')];if(q('fpvFlash')&&statusBoxes.length)q('fpvFlash').checked=statusBoxes.some(b=>b.querySelector('.fps-flash-rec')?.checked)}
function defaults(){const vals={osd1:'{batt}',osd2:'{state} {recdur}',osd3:'{mode} {res} {fps} {eis}',osd4:'{rectf} {rcap}',pilotTpl:'{batt}',craftTpl:'{state} {recdur}'};for(const[id,v]of Object.entries(vals))if(q(id)){q(id).value=v;q(id).dispatchEvent(new Event('input',{bubbles:true}))}if(q('fpvPreArmText'))q('fpvPreArmText').value='';if(q('fpvPreArm'))q('fpvPreArm').checked=true;if(q('fpvCustomDurationSec'))q('fpvCustomDurationSec').value='1.0';if(q('fpvLowBatt'))q('fpvLowBatt').checked=true;if(q('fpvLowPct'))q('fpvLowPct').value='10';if(q('fpvRecLowMin'))q('fpvRecLowMin').value='5';sync()}
function init(){const labels={osd1:'Custom Message 1',osd2:'Custom Message 2',osd3:'Custom Message 3',osd4:'Custom Message 4',pilotTpl:'Pilot Name',craftTpl:'Craft Name'};for(const id of IDS)if(q(id))makeBuilder(q(id),labels[id]);const reset=document.createElement('button');reset.type='button';reset.id='fpsResetDefaults';reset.textContent='Reset to FPSteVe defaults';reset.onclick=()=>{if(confirm('Reset the visible FPSteVe settings to defaults? You can review them before Apply.'))defaults()};const footer=document.querySelector('#panel-config .card-footer');if(footer)footer.insertBefore(reset,footer.firstChild);q('bf45Compat')?.addEventListener('change',sync);sync()}
const css=document.createElement('style');css.textContent='.fps-builder{margin:10px 18px 16px;padding:12px;border:1px solid #6d28d9;border-radius:10px;background:rgba(109,40,217,.09)}.fps-builder-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:9px}.fps-preview{font:12px monospace;color:#c4b5fd}.fps-picker>summary{cursor:pointer;border:1px solid #6d28d9;border-radius:6px;padding:7px 9px;list-style:none}.fps-picker>summary:after{content:" ▾"}.fps-menu{display:grid;grid-template-columns:1fr 1fr;gap:5px 12px;padding:10px;border:1px solid #6d28d9;border-top:0;border-radius:0 0 6px 6px}.fps-menu label{display:flex;align-items:center;gap:7px;cursor:pointer}.fps-chips{display:flex;flex-wrap:wrap;gap:6px;margin:9px 0}.fps-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border:1px solid #7c3aed;border-radius:999px;background:rgba(124,58,237,.15)}.fps-chip button{border:0;background:transparent;padding:0 2px;font-size:16px;color:inherit}.fps-local-status{display:grid;gap:7px;margin:9px 0;padding:9px;border-left:2px solid #8b5cf6;background:rgba(124,58,237,.08)}.fps-local-status label{display:flex;gap:8px;align-items:center}.fps-advanced{font-size:11px}.fps-builder .tpl-input{margin-top:8px}.fps-disabled{opacity:.35;pointer-events:none}.fps-hidden{display:none!important}#fpsResetDefaults{margin-right:auto}';document.head.appendChild(css);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
